### PR TITLE
Check for slurm earlier in the process

### PR DESCRIPTION
**Pull request by jcftang**
This relates to https://github.com/dask/dask-drmaa/pull/33 I just moved the changes to the create job templates method

However slurm-drmaa segfaults on me and I can't actually use it.

### CODE REVIEW

**Comment by jakirkham** [comment]
Were you meaning to send this upstream?

**Comment by jcftang** [comment]
@jakirkham ah I was wondering why no one was commenting on it :P

**Comment by jcftang** [comment]
closing this pr, I made a mess of it.

**Comment by jakirkham** [comment]
No worries. Only caught it thanks to the xref. Glad it got sorted. Guessing this is PR ( https://github.com/dask/dask-drmaa/pull/46 )?

**Comment by jcftang** [comment]
Yes, #46 is the same as the previous botched PR

**Comment by jakirkham** [comment]
Ok, thanks.

**Pull request closed without merging**
